### PR TITLE
pkg templates

### LINKED ISSUE #17: Missing templates in sensorml2iso conda package from conda-forge
Hi! 

I installed `sensorml2iso` from  conda-forge into a new conda environment, then trying to run it, I get a `TemplateNotFound` error:

```bash
$ sensorml2iso -s http://data.nanoos.org/52nsos/sos/kvp --output_dir $ISOPATH
Success, no errors returned from DescribeSensor requests in service: http://data.nanoos.org/52nsos/sos/kvp?acceptVersions=1.0.0&request=GetCapabilities&service=SOS
Traceback (most recent call last):
  File "/home/lsetiawan/miniconda/envs/test/bin/sensorml2iso", line 6, in <module>
    sys.exit(sensorml2iso.command_line.main())
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso/command_line.py", line 98, in main
    obj.run()
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso/sensorml2iso.py", line 171, in run
    self.generate_iso(stations_df)
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso/sensorml2iso.py", line 485, in generate_iso
    template = env.get_template('sensorml_iso.xml')
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sensorml_iso.xml
```

I went to `/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso` and `sensorml_iso.xml` is indeed nowhere to be found. 

```bash
$ ls /home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso/
command_line.py  command_line.pyc  __init__.py  __init__.pyc  sensorml2iso.py  sensorml2iso.pyc
```

Looking at the [main repo](https://github.com/ioos/sensorml2iso/tree/master/sensorml2iso) of this package, it seems like the `templates` folder did not get included in the conda package. 

CC. @ocefpaf @emiliom

### PR DESCRIPTION
**Pull request by ocefpaf**
The `template` xml files did not make into the final folder.

Closes #17

### CODE REVIEW

**Comment by emiliom** [comment]
Wow, thanks for the fast action, @ocefpaf! (and @lsetiawan for submitting the issue) I'm glad it was an easy fix.

**Comment by mwengren** [comment]
@ocefpaf so the issue is that setup.py doesn't properly build the package via [this command](https://github.com/conda-forge/sensorml2iso-feedstock/blob/master/recipe/meta.yaml#L14) in the feedstock?  The release archive does contain the templates, but I guess that's not what conda-forge actually uses? Just trying to understand.  I see the error in my original setup.py though.  I think I never noticed because I only tested locally via `pip install -e .`

**Comment by ocefpaf** [comment]
> @ocefpaf so the issue is that setup.py doesn't properly build the package via [this command](https://github.com/conda-forge/sensorml2iso-feedstock/blob/master/recipe/meta.yaml#L14) in the feedstock? 

Yep.

> The release archive does contain the templates, but I guess that's not what conda-forge actually uses? 

It is not a `conda-forge` thing but how python searches for the packaged files.

> Just trying to understand.  I see the error in my original setup.py though.  I think I never noticed because I only tested locally via `pip install -e .`

`pip install -e .` is  meant for developing and not production. That was hindering the `pkg_data` bug b/c those files where present in the repo but won't be once the module is properly installed.

I am also sending a PR to change the `.travis.yml` to fix that.

**Comment by mwengren** [comment]
Great... I knew that mostly but never fully tested the `python setup.py install`.... can we also include this module in the IOOS Conda environment files once it's proven to be working properly?   The Readme should also probably be updated, installation notes.

**Comment by mwengren** [comment]
Since I have your attention though @ocefpaf .... what's the [source block](https://github.com/conda-forge/sensorml2iso-feedstock/blob/master/recipe/meta.yaml#L7-#L10) used for in the conda-forge recipe then?

**Comment by ocefpaf** [comment]
> Since I have your attention though @ocefpaf .... what's the [source block](https://github.com/conda-forge/sensorml2iso-feedstock/blob/master/recipe/meta.yaml#L7-#L10) used for in the conda-forge recipe then?

```yaml
source:
  fn : sensorml2iso-{{ version }}.tar.gz
  url: https://github.com/ioos/sensorml2iso/archive/v{{ version }}.tar.gz
  sha256: 7ca52c28264ef462747c32432f6023a1857ae882d687424994394700b40b7482
```

- `fn` is no longer needed with latest `conda-build` but it is nice to add it there for clarityk
- `url` is where we get the source code;
- `sha256` is the checksum to ensure the source is OK.

They are used to get the source for the build. 

But my guess is that you are not understanding the difference from `pip install -e .` and `pip install` (equivalent to `python setup.py install` in this case). The former will drop a symlink'ed `.egg` giving you the illusion that the package data was properly packaged. The latter will properly install the module at `site-packages`.

BTW I never develop with `pip install -e` to avoid failing into that trap. It is easy enough to create a `venv` and install the module while developing IMO.

**Comment by mwengren** [comment]
Ok, thanks, the source explanation helps.  I knew about the `python setup.py install` differences vs. `pip install -e .` but I admit guilt in cutting some corners :).  I meant to clean this up some more before we merged it into conda-forge, but you guys were too quick for me!  It is nice to know more about how conda-forge works though and the proper way to package a python module, Travis-CI configuration, etc.

**Comment by ocefpaf** [comment]
I don't recall why we had it package on `conda-forge` but that is quite normal with new modules and we only found out because we package it, so it is a win-win :wink:

**Pull request merged**
