### PR TITLE
add windows testing

### PR DESCRIPTION
**Pull request by ocefpaf**
This may need some tweaking.
Note that someone with the proper rights must set AppVeyor for this repository.

### CODE REVIEW

**Comment by mwengren** [comment]
@ocefpaf sorry I haven't been paying attention to GitHub/PRs for my various repositories for some time.  Should this still be merged?  What needs to be done to set AppVeyor?

**Comment by mwengren** [comment]
I'll go ahead and merge.  I think I enabled AppVeyor, we'll see....

**Comment by ocefpaf** [comment]
I never remember on top of my head the steps to enable AppVeyor but I guess you can loging with tour GitHub account and follow the links. I'll try to re-do that locally and maybe record a video to help us in the future.

Regarding this PR, it probably needs an updated. I'll check once AppVeyor is running again.

**Comment by mwengren** [comment]
Ok, I merged it anyway, and registered the repo in AppVeyor. The build passed fwiw, so probably can leave it as is, but I'll try to keep on top of these a little more. I didn't see an AppVeyor notice next to the Travis icon, but that's not a big deal.

**Comment by ocefpaf** [comment]
>  I didn't see an AppVeyor notice next to the Travis icon, but that's not a big deal.

We have to edit the README to put the badge there but new PRs should show the status after you enabled it. To get the badge URL you can navigate to:

https://ci.appveyor.com/project/mwengren/sensorml2iso/settings/badges

BTW, we should create a "dummy" robot account on GitHub and so we can add multiple people with access to AppVeyor to avoid having a single point of failure. We did that for the model testbed with the comt-robot.

**Pull request merged**
