### PR TITLE
Docker Integration

### PR DESCRIPTION
**Pull request by lukecampbell**
This integration step brings together to use cases for sensorml2iso. The first use case is wrapping the command line interface for sensorml2iso in a docker container so that users can pull, run and integrate sensorml2iso through docker.

```
docker run -v $HOME/Desktop/WAF:/srv/iso --name test -it --rm ioos/sensorml2iso -s http://sos.glos.us/52n/sos/kvp --output_dir /srv/iso/glos
```

The second use case which I needed for IOOS Catalog was deploying the project as a service that would occasionally run and update a WAF. It's less of a service and more of a cron job.

Originally my approach was to use baseimage and setup a cron job but @benjwadams pointed out that it's overkill and the image was 700MiB compressed. @daf pointed out that there was a much better approach if we used ENTRYPOINT so that we can support both simultaneously.

This approach was much better in that it was consistent with the first use case, and the image was considerably smaller.

It would be good for @shane-axiom and @daf to make sure that this change doesn't break any workflow they already have.

### CODE REVIEW

**Review by mwengren — APPROVED** [review]
We really need some real tests for this module (was too lazy to write them myself), but no objection here.

**Review by daf — APPROVED** [review]
Seems fine.  I notice it still has a valid co-ops config - is that simply used as a sample or should that configuration be made more explicit - if you don't configure/derived your own image, should it simply print usage or that section from the README?

**Comment by daf** [comment]
Also, wouldn't you want to be able to run sensorml2iso as if it were a command line tool via docker, not just use it in a scheduled manner?

**Comment by lukecampbell** [comment]
You can run it as a command line tool, if you pass in any arguments the entry point runs the command line tool instead of the cron daemon. The config is meant to serve as an example, and it just so happens the default is handy for where we have it deployed for the IOOS catalog.

**Comment by daf** [comment]
Ah, I've re-read the README and see what you mean. Thanks.

**Pull request merged**
